version: 2
updates:
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snowpack
    versions:
    - 3.0.11
    - 3.0.13
    - 3.1.2
    - 3.2.2
    - 3.3.0
    - 3.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lit-html
    versions:
    - 1.3.0
